//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginFormMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int id { get; set; }

        [DisplayName("USERNAME")]
        [Required(ErrorMessage ="UserName is Required")]
        public string Username { get; set; }

        [DisplayName("PASSWORD")]
        [Required(ErrorMessage = "Password is Required")]

        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}
